import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home({ pokemon }) {
  console.log(pokemon);
  return (
    <>
      <Head>
        <title>pokemon | app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.BgImageDiv}>
          <img className={styles.BgImage} src="/Assets/Background.png" alt="background-image" />
          <img className={styles.logo} src="/Assets/logo.png" alt="logo" />
        </div>
        <div className={styles.cardContainer}>
          <div className={styles.grid}>
            {pokemon.results.slice(0, 10).map((poke, index) => (
              <Link href={`/pokemon/${pokemon.name}`} key={index} legacyBehavior>
                <div className={styles.card}>
                  <div className={styles.innerImageDiv}>
                    <a>
                      <p className={styles.counterNumber}>#{("000" + (index + 1)).slice(-3)}</p>
                      <img className={styles.cardImage} src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${index + 1}.png`} alt="" />
                    </a>
                  </div>
                  <div className={styles.buttonDiv}>
                    <p className={styles.pokemonName}>{poke.name}</p>
                    <div className={styles.buttons}>
                      <a href="/">Grass</a>
                      <a href="/">Poison</a>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
        {/* Second Part================= */}
        <div className={styles.secondMain}>
          <div className={styles.titleDiv}>
            <img className={styles.brush} src="/Assets/Brush.png" alt="brush" />
            <h1 className={styles.titles}>
              Ash & Pikachu Arrive in <br /> <span>Pokemon Universe</span>
            </h1>
          </div>
          <div className={styles.left__right__images__div}>
            <img className={styles.leftImage} src="/Assets/Left.png" alt="left" />
            <img className={styles.rightImage} src="/Assets/Left.png" alt="left" />
          </div>
          {/* -------------grid section-------------------- */}
          <div className={styles.grid__section}>
            <div className={styles.grid__column}>
              <div className={styles.left__column}>
                <div className={styles.left_sub_row_one}>
                  <img className={styles.left_image__one} src="/Assets/image03.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. final form of Raichu. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.left_sub_row_one}>
                  <img className={styles.left_image_two} src="/Assets/image02.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.left_sub_row_one}>
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. and is the final form of Raichu.
                  </p>
                </div>
              </div>
              <div className={styles.right_column}>
                <div className={styles.right_sub_row_one}>
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.right_sub_row_two}>
                  <img className={styles.right_image__one} src="/Assets/image05.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.right_sub_row_three}>
                  <img className={styles.right_image_two} src="/Assets/image01.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with
                    red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears. cheeks, black-tipped.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const res = await fetch("https://pokeapi.co/api/v2/pokemon");
  const pokemon = await res.json();

  return {
    props: {
      pokemon,
    },
  };
}
