import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { gql } from "@apollo/client";
import { client } from "./_app.js";

export default function Home({ data }) {
  const pokemons = data.pokemons.results;
  console.log(pokemons);
  return (
    <>
      <Head>
        <title>pokemon | app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.BgImageDiv}>
          <img className={styles.BgImage} src="/Assets/Background.png" alt="background-image" />
          <img className={styles.logo} src="/Assets/Logo.png" alt="logo" />
        </div>
        <div className={styles.cardContainer}>
          <div className={styles.grid}>
            {pokemons.slice(0, 10).map((poke, index) => (
              <Link
                href={{
                  pathname: `/pokemon/${poke.name}`,
                  query: { count: index + 1 },
                }}
                key={index}
                legacyBehavior
              >
                <div className={styles.card}>
                  <div className={styles.innerImageDiv}>
                    <a>
                      <p className={styles.counterNumber}>#{("000" + (index + 1)).slice(-3)}</p>
                      <img className={styles.cardImage} src={poke.image} alt="image" />
                    </a>
                  </div>
                  <div className={styles.buttonDiv}>
                    <p className={styles.pokemonName}>{poke.name}</p>
                    <div className={styles.buttons}>
                      <a href="/">Grass</a>
                      <a href="/">Poison</a>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
        {/* =============Second Part================= */}
        <div className={styles.secondMain}>
          <div className={styles.titleDiv}>
            <img className={styles.brush} src="/Assets/Brush.png" alt="brush" />
            <h1 className={styles.titles}>
              Ash & Pikachu Arrive in <br /> <span>Pokemon Universe</span>
            </h1>
          </div>
          <div className={styles.left__right__images__div}>
            <img className={styles.leftImage} src="/Assets/Left.png" alt="left" />
            <img className={styles.rightImage} src="/Assets/Left.png" alt="left" />
          </div>
          {/* -------------grid section-------------------- */}
          <p className={styles.top_content}>
            Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu and is the
            final form of Raichu. Pikachu is known for.
          </p>
          <p className={styles.bottom_content}>
            Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu and is the
            final form of Raichu. Pikachu is known for its cute and cheerful known for. black- Pikachu is known.black-tipped ears, and a lightning bolt-shaped black-tipped.
          </p>
          <div className={styles.grid__section}>
            <div className={styles.grid__column}>
              <div className={styles.left__column}>
                <div className={styles.left_sub_row_one}>
                  <img className={styles.left_image__one} src="/Assets/Image03.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. final form of Raichu. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.left_sub_row_one}>
                  <img className={styles.left_image_two} src="/Assets/Image02.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.left_sub_row_one}>
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. and is the final form of Raichu.
                  </p>
                </div>
              </div>
              <div className={styles.right_column}>
                <div className={styles.right_sub_row_one}>
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.right_sub_row_two}>
                  <img className={styles.right_image__one} src="/Assets/Image05.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. Pikachu is known for its cute and cheerful known for.
                  </p>
                </div>
                <div className={styles.right_sub_row_three}>
                  <img className={styles.right_image_two} src="/Assets/Image01.png" alt="img" />
                  <p className={styles.image_one_description}>
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu
                    and is the final form of Raichu. Pikachu is known for its cute and cheerful known for. Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with
                    red cheeks, black-tipped ears, and a lightning bolt-shaped tail. It evolves from Pichu and is the final form of Raichu. Pikachu is known for its cute and cheerful known for.
                    Pikachu is a popular Electric-type Pokémon that has the appearance of a yellow rodent with red cheeks, black-tipped ears. cheeks, black-tipped.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query pokemons {
        pokemons {
          count
          next
          previous
          nextOffset
          prevOffset
          status
          message
          results {
            url
            name
            image
          }
        }
      }
    `,
  });

  return {
    props: {
      data,
    },
  };
}
